---
abstract: 'Interface to the password filter.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Mouse: 0.93
  Readonly: 1.03
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Password-Filter
provides:
  Data::Password::Filter:
    file: lib/Data/Password/Filter.pm
    version: 0.05
  Data::Password::Filter::Dictionary:
    file: lib/Data/Password/Filter/Dictionary.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
